✨ Icon component
engagor/unified-components-react pull request #13
Opened 2021-07-09 09:06 UTC by thaoms

### Summary
Adding an Icon component

### Checklist
- [x] Component is added to Storybook
- [x] Component is tested

2021-07-09 09:27 UTC, matthias-deschoenmacker approved these changes

2021-07-09 15:09 UTC, cedricengagor approved these changes

2021-07-09 15:11 UTC, cedricengagor requested changes

2021-07-09 15:11 UTC, cedricengagor commented on src/icon/Icon.tsx
> +    return <span className={`en-icon en-icon-${props.iconName} ${props.className}`} aria-hidden="true" />
```suggestion
    return <span className={`en-icon en-icon-${props.iconName} ${props.className ?? ''}`} aria-hidden="true" />
```

Since this is optional you need to pass it a fallback. Spotted this in the snapshot below :trollface:

2021-07-12 07:17 UTC, cedricengagor approved these changes
👏

2021-07-13 09:19 UTC, goOve approved these changes

2021-07-13 12:02 UTC, merged