✨ Divider component
engagor/unified-components-react pull request #17
Opened 2021-07-09 10:55 UTC by thaoms

### Summary
Added divider component

### Checklist
- [x] Component is added to Storybook
- [x] Component is tested

2021-07-09 15:01 UTC, cedricengagor requested changes
REQ: Component looks good, some mistakes in the tests and es lint issues tho

- Divider.text.tsx => Divider.test.tsx
- ESLint stuff 🙇

2021-07-12 07:23 UTC, cedricengagor approved these changes

2021-07-12 07:31 UTC, matthias-deschoenmacker approved these changes

2021-07-13 09:24 UTC, goOve approved these changes

2021-07-13 12:03 UTC, merged