✨ added two new component
engagor/unified-components-react pull request #237
Opened 2022-03-02 13:57 UTC by Aimanoshi

Added assetPicker: a gif picker with a search bar
Added image in folder Element: a simple image component

### Summary
Component that shows the gifs.

### Checklist
- [ x] Component is added to Storybook
- [ ] Component is tested

2022-03-03 09:20 UTC, cedricengagor commented on src/AssetPicker/AssetPicker.spec.tsx
> +describe('Input field', () => {
Seems that this was forgotten, should probably be AssetPicker 🙇

2022-03-03 09:21 UTC, cedricengagor commented on src/AssetPicker/AssetPicker.tsx
> +                <>
Q: Why did we use a React.Fragment here?

2022-03-03 09:28 UTC, cedricengagor commented on src/AssetPicker/AssetPicker.tsx
> +const AssetPicker = forwardRef<HTMLDivElement, AssetPickerProps>(
REQ: Currently this component seems to be quite static, in order to make this work this component should probably perform some kind of api call (fetch API, axios, ...) to retrieve the required external assets from the service. Afterwards it will allow someone to click on the displayed images which should trigger a handler passed using the props of this component.

What I'm missing right now:
- Fetching of data on load of component => with appropriate loading and empty states
- Click handler passed via props => `onAssetClick: (asset: Asset) => void`
- I'd assume that the isOpen state is maintained by this component or otherwise you're missing other click handlers as well
- Compatibility for dark mode, you can define utilities like `dark:border-charcoal-color-100` for example

2022-03-03 09:28 UTC, cedricengagor commented on src/AssetPicker/AssetPicker.tsx
> +    ) {
REQ: Missing return type? Is editor configured correctly?

2022-03-03 09:29 UTC, cedricengagor commented on src/Elements/Image.tsx
> +    ) {
REQ: Missing return type

2022-03-03 09:30 UTC, cedricengagor commented on src/Elements/Image.tsx
> +        const calculateWidth = { width: 'calc(50% - (1vh/2))' };
Q: Why did we use the viewport height as calculation for the width? What would be other/better ways to solve this?

2022-03-03 09:30 UTC, cedricengagor commented on src/Elements/Image.tsx
> +            <div role="img" aria-label={alt} style={ calculateWidth } className='overflow-hidden inline-block border-charcoal-color-300 border-solid border-1 rounded-4 hover:border-primary-color-300'
REQ: Make sure to maintain consistent code styles, like `"` for the attributes instead of `'` as used for className here.

2022-03-03 09:31 UTC, cedricengagor commented on src/Elements/Image.tsx
> +                <img aria-hidden="true" className="block max-w-100-percent h-auto" src={image} alt={alt}/>
Q: We did we make this aria-hidden?

2022-03-03 09:31 UTC, cedricengagor commented on webpack.config.js
> +                    'css-loader',
Q: Why this change? Seems not needed and prolly a configuration thing in the editor.

2022-03-03 09:32 UTC, cedricengagor commented on stories/Elements/Divider.stories.tsx
> +import Divider, { DividerProps } from '../../src/Elements/Divider';
Q: Was this a bug?

2022-03-03 10:51 UTC, Aimanoshi commented on stories/Elements/Divider.stories.tsx
> +import Divider, { DividerProps } from '../../src/Elements/Divider';
I but the divider and image in a separate folder called elements like in the src code. Is it okay our should I change it?

2022-03-03 10:53 UTC, Aimanoshi commented on webpack.config.js
> +                    'css-loader',
That was a mistake I made.

2022-03-03 10:57 UTC, Aimanoshi commented on src/Elements/Image.tsx
> +        const calculateWidth = { width: 'calc(50% - (1vh/2))' };
I changed it to vw. Is that better or do you mean something else?

2022-03-03 11:02 UTC, Aimanoshi commented on src/AssetPicker/AssetPicker.tsx
> +const AssetPicker = forwardRef<HTMLDivElement, AssetPickerProps>(
I will implement them.

2022-03-08 08:51 UTC, thaoms requested changes
I might have more but first lets fix these ones

2022-03-08 08:51 UTC, thaoms commented on src/AssetPicker/AssetPicker.spec.tsx
> +    })
end with a ; and a new line after every assert

2022-03-08 08:51 UTC, thaoms commented on src/AssetPicker/AssetPickerContent.tsx
> +        if (props.Gifs.length === 0){
only lowercase characters pls

2022-03-08 08:51 UTC, thaoms commented on src/AssetPicker/AssetPickerContent.tsx
> +            if (props.onAssetClick) {
I wouldn't add a guard here and make it a required prop

2022-03-08 08:51 UTC, thaoms commented on src/AssetPicker/AssetPickerContent.tsx
> +            return <p className="text-charcoal-color-300 text-center text-lg-4"> Loading...</p>
Maybe we can show an animated spinner?

2022-03-08 08:51 UTC, thaoms commented on stories/AssetPicker.stories.tsx
> +            'name': 'Sexy Happy Birthday GIF',
🍆

2022-03-08 08:51 UTC, thaoms commented on src/AssetPicker/AssetPickerContent.tsx
> +        const spaceBetween = { gap:'1vw' };
I will make a release this friday with the gap functionality

2022-03-08 08:51 UTC, thaoms commented on src/AssetPicker/AssetPickerContent.tsx
> +import React, { forwardRef, PropsWithChildren } from 'react';
Some Type errors need fixing

2022-03-08 08:51 UTC, thaoms commented on src/AssetPicker/AssetPicker.tsx
> +                <input className="mb-16 p-16 border-solid border-charcoal-color-300 border-1 rounded-2 dark:bg-charcoal-color-600 dark:text-white" id="search" type="search" placeholder="Search"></inp
Just semantics but I would use a more specific id for the input , you never know where we will render this one, and search already exists there. Maybe asset-search, or something

2022-03-08 08:51 UTC, thaoms commented on src/AssetPicker/AssetPicker.tsx
> +    const loading = false;
I guess this will need to switch to a state when you start fetching real stuff.

2022-03-08 08:51 UTC, thaoms commented on src/AssetPicker/AssetPicker.tsx
> +export default function AssetPicker(props: AssetPickerProps) {
Maybe add a return value here.

2022-03-08 08:51 UTC, thaoms commented on src/AssetPicker/AssetPicker.tsx
> +export type AssetPickerProps = PropsWithChildren<{
a new line between here

2022-04-08 08:41 UTC, matthias-deschoenmacker commented on src/AssetPicker/AssetPicker.tsx
> +        const trendingGifs = await get(( keyword !== '' ? `/search/${keyword}` : '/trending') + segment);
Would call this `loadedGifs` or something similar since you only fetch trending gifs if the keyword is emptry

2022-04-08 08:41 UTC, matthias-deschoenmacker commented on src/AssetPicker/AssetPicker.tsx
> +        if (trendingGifs.assets === undefined) { return setAssets(oldArray => [...oldArray])}
Multilining this is a bit more clear

```suggestion
        if (trendingGifs.assets === undefined) { 
            return setAssets(oldArray => [...oldArray]);
        }
```

2022-04-08 08:41 UTC, matthias-deschoenmacker commented on src/AssetPicker/AssetPicker.tsx
> +        if (response.ok) setAssets(oldArray => [...oldArray, ...trendingGifs.assets])
Multilining this is a bit more clear and definitely always us { } for ifs

```suggestion
        if (response.ok) {
            setAssets(oldArray => [...oldArray, ...trendingGifs.assets]);
        }
```

2023-02-14 20:34 UTC, closed without merging