Add contributing section
engagor/unified-components-react pull request #6
Opened 2021-04-30 14:03 UTC by Toinne

2021-04-30 14:04 UTC, thaoms approved these changes

2021-04-30 14:06 UTC, cedricengagor requested changes

2021-04-30 14:06 UTC, cedricengagor commented on .github/PULL_REQUEST_TEMPLATE.md
> +    - [ ] High contrast mode
Maybe leave this on out for now, until we've decided on how to proceed with it

2021-04-30 14:06 UTC, cedricengagor commented on README.md
> +Components that are added to this repository should be pre-approved by the design team. Only unified components that adhere to the global brand guidelines are added.
PP: Lets add that diagram I made here, should be the guideline on how to add components 🙇

2021-05-04 11:55 UTC, cedricengagor approved these changes

2021-05-07 08:07 UTC, merged