♻️  Renamed Switch Button to Toggle [CB-15862]
engagor/unified-components-react pull request #74
Opened 2021-09-17 07:55 UTC by thaoms

Fixes CB-15862

2021-09-17 08:11 UTC, cedricengagor commented on src/Buttons/Toggle.tsx
>  import '@clarabridge/unified-ui/dist/switch-buttons.css';
Q: Can you also open a PR on `unified-ui` to rename this to switch-btn together with it's classnames?

2021-09-17 08:20 UTC, thaoms commented on src/Buttons/Toggle.tsx
>  import '@clarabridge/unified-ui/dist/switch-buttons.css';
This is the last time I do a rename after a feature is made..

2021-09-20 07:10 UTC, matthias-deschoenmacker approved these changes

2021-10-15 09:49 UTC, thaoms commented
This one need sot be merged first + package update should then be included in this PR
https://github.com/ClarabridgeInc/unified-ui/pull/100

2021-10-19 10:30 UTC, cedricengagor requested changes
REQ: You still need to install the package version increase. Test is indicating that 🙇

2021-11-05 10:05 UTC, cedricengagor approved these changes

2021-11-05 10:06 UTC, merged