✨ Added basic dropdown with utilities
engagor/unified-components-react pull request #9
Opened 2021-05-07 12:57 UTC by thaoms

2021-05-10 07:23 UTC, cedricengagor reviewed
Lets also think about the way that we would use this component. At the moment we don't have anything that renders it based on the trigger. Maybe we should add a component there for this as well. Or maybe we should still interpret this in the dropdown. Cause I think if we give too much freedom for this people will misuse the component 🙇

2021-05-10 07:23 UTC, cedricengagor commented on src/dropdowns/DropdownItem.tsx
> +type DropdownItem = {
PP: Would probably rename to Props or something. This way it wont collide with the actual component when we'd have to export it 🙇

2021-05-10 07:23 UTC, cedricengagor commented on src/dropdowns/DropdownItem.tsx
> +            }
Q: Would it make sense to apply the padding on the `option` and pass the correct html element in the usage of the dropdown? This way the dropdown doesn't handle much except for the visual aspect 🙇

2021-08-13 10:06 UTC, cedricengagor approved these changes

2021-08-16 13:01 UTC, matthias-deschoenmacker approved these changes
Code looks good to me

2021-08-18 12:36 UTC, marcusrelacion requested changes

2021-08-18 12:36 UTC, marcusrelacion commented on src/Dropdowns/DropdownItem.tsx
> +        'bg-primary-color-600',
`bg-primary-color-600` should be `bg-primary-color-500`

2021-08-18 12:36 UTC, marcusrelacion commented on src/Dropdowns/DropdownList.tsx
> +                className="shadow rounded-8 bg-white dark:bg-charcoal-color-500 min-w-320 max-w-400 overflow-hidden"
`rounded-8` should be `rounded-4`

2021-08-18 12:36 UTC, marcusrelacion commented on src/Dropdowns/DropdownItem.tsx
> +        'bg-primary-color-600',
Not seeing where the border color is set for the divider, but the divider should use `border-charcoal-300`.

2021-08-25 07:36 UTC, goOve approved these changes

2021-08-30 07:51 UTC, merged